[build]
  base = "backend"
  command = "npm run build"
  publish = "backend"
  functions = "backend/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true