name: Deploy Fullstack App (Backend + Frontend) to Azure

on:
  push:
    branches:
      - pre-prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend into backend
        working-directory: frontend
        run: |
          npm run build
          cp -r dist ../backend/public

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure this secret is set in GitHub repository settings

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: TuniFlow
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: backend