name: Deploy Fullstack App (Backend + Frontend) to Azure

on:
  push:
    branches:
      - pre-prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Build frontend into backend
        run: |
          cd frontend
          npm install
          npm run build
          cp -r build ../backend/

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: TuniFlow
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: backend
